name: MovieAnalystAPP
on: [push]

jobs:
  job_1_terraform_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Verify Terraform Version
      run: terraform --version

  job_2_azure_environment:
    runs-on: ubuntu-latest
    needs: job_1_terraform_version
    env:
        ARM_CLIENT_ID: ${{ secrets.TF_VAR_agent_client_id }}
        ARM_CLIENT_SECRET: ${{ secrets.TF_VAR_agent_client_secret }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_subscription_id }}
        ARM_TENANT_ID: ${{ secrets.TF_VAR_tenant_id }}
    steps:
    - uses: actions/checkout@v1  
    - name: Terraform Initialization
      working-directory: terraform/
      run: terraform init
    - name: Terraform Validation
      working-directory: terraform/
      run: terraform validate
    - name: Terraform Planing
      working-directory: terraform/
      run: terraform plan
    - name: Terraform apply
      working-directory: terraform/
      run: terraform apply -auto-approve
    - name:
      working-directory: terraform/
      run: bash data.sh
